all:
	gcc -oFast bb_prototype.c -o bb_proto
	x86_64-w64-mingw32-gcc -oFast bb_prototype.c -o bb_proto.exe

debug:
	gcc bb_prototype.c -o bb_proto
	x86_64-w64-mingw32-gcc bb_prototype.c -o bb_proto.exe
